### ISSUE TITLE
Implement the gremlin traversal strategy to bypass V() and E()

### ISSUE THREAD

**Issue by vsantosu** [TruenoDB/trueno#4]
We need to bypass fetching all 10000(limit) from the backend. Research how to go to the next traversal step to see if there is a filter to narrow down the results. This will make the search orders of magnitude faster.

Also, the issue is that if the searched component is further than the first 10,000 results, it wont find it.

**Comment by ebarsallo** [comment]
A partial solution was added for vertices on [0aa66c527d5ca04dcd1ae68f1b30045f61cd6dfd](https://github.com/TruenoDB/trueno-gremlin/commit/0aa66c527d5ca04dcd1ae68f1b30045f61cd6dfd). Now the traversal use indexes for _vertices_ searches like g.V().

Still **pending** to implement a traversal strategy for _edges_, also implement an iterator that retrieve data in **neighbor** and **fetch** operation in an stream fashion (retrieving data by chunks).
